name = "next-project-programs"
version = "0.1.0"
authors = [""]

[[programs]]
path = "src/main.py"
name = "main"
prime_size = 128

[[programs]]
path = "src/addition_simple.py"
name = "addition_simple"
prime_size = 128

[[programs]]
path = "src/tiny_secret_addition.py"
name = "tiny_secret_addition"
prime_size = 128

[[programs]]
path = "src/secret_calculator.py"
name = "secret_calculator"
prime_size = 128
